name: PR Development
on:
  pull_request:
   types: [opened, synchronize, reopened ,edited,review_requested]
   branches:
      - development
jobs:
 branch_name:
  name: Branch name convention
  runs-on: ubuntu-latest
  steps:
   - uses: deepakputhraya/action-pr-title@master
     with:
             allowed_prefixes: 'feat,wip,bug,junk,refactor' # title should start with the given prefix
             prefix_case_sensitive: false # title prefix are case insensitive
             min_length: 5 # Min length of the title
             max_length: 50
             github_token: ${{ github.token }} # Default: ${{ github.token }}

 tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Pull request to Dev made'
 sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
