name: Development
on:
  pull_request:
   types: [opened, synchronize, reopened ,review_requested]
   branches:
      - development
jobs:
  write-to-console:
    name: Development PR 
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Pull request to Dev made'
