name: Master
on:
  pull_request:
   types: [opened, synchronize]
   branches:
      - master
jobs:
  write-to-console:
    name: Master PR 
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Pull request with master as the base branch'
