name: Deploy dev to INT
on: 
 push:
  branches:
  - development
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running tests'
  
  deploy: 
   needs: tests
   runs-on: ubuntu-latest
   steps:
      - run: echo 'deploying'