name: Deploy master to STG 
on: 
 push:
  branches:
  - master
jobs:
  tests:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running tests'
  
  deploy: 
   name: Deploying to stg
   needs: write-to-console
   runs-on: ubuntu-latest