name: Deploy master to STG 
on: 
 push:
  branches:
  - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running tests'
  
  deploy: 
   needs: tests
   runs-on: ubuntu-latest
   if: always()
   steps:
      - run: echo 'deploying'